---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-secrets-editor
  namespace: ecr-public-creds-helper
---
# As you may realized, this is not the minimum permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-editor
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edit-secrets
subjects:
- kind: ServiceAccount
  name: sa-secrets-editor
  namespace: ecr-public-creds-helper
roleRef:
  kind: ClusterRole
  name: secrets-editor
  apiGroup: rbac.authorization.k8s.io
